Modified package.json: Reverted change to id - this cannot be changed once an add-on has been submitted to Mozilla.
Modified data/jquery.js: Fixed the following issue that was reported by the Mozilla add-on validator:

*JS reflection error prevented validation*
Error: An error in the JavaScript file prevented it from being properly read by the Spidermonkey JS engine.
'1:0 warning: Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead\n'

Added data/widget.png: Forgot to commit the icon for the widget.